# Generated by Django 4.0.2 on 2022-05-29 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='author', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='followed_blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
